version: '3'

services:
    app:
        image: webdevops/php-dev:8.1
        container_name: dti
        working_dir: /app
        env_file:
            - ./.env
        volumes:
            - ../../:/app
            - ~/.ssh:/root/ssh:ro
        networks:
            - network

    minio:
        image: minio/minio
        container_name: dti-minio
        ports:
            - 9000:9000
        volumes:
            - ${DATA_PATH_HOST}/mino/data:/export
            - ${DATA_PATH_HOST}/minio/config:/root/.minio
        environment:
            MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
            MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
        networks:
            - network

    mysql:
        image: mysql:8
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - TZ=${TIMEZONE}
        volumes:
            - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
            - ../conf/mysql-init.d:/docker-entrypoint-initdb.d
        ports:
            - "3306:3306"
        networks:
            - network

    adminer:
        image: adminer
        environment:
            - ADMINER_DEFAULT_SERVER=mysql
        restart: always
        ports:
            - 8080:8080
        networks:
            - network
networks:
    network:
        driver: bridge
